# Generated by Django 4.0.7 on 2022-10-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='DEF',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='DRI',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='PAC',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='PAS',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='PHY',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='SHO',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
